### ISSUE TITLE
cant compile any version of 23.05 after released 23.05.4 for zyxel p2812

### ISSUE THREAD

**Issue by mbunal** [openwrt/firmware-selector-openwrt-org#23]
I choose ZyXEL P-2812HNU F1. I click "Customize installed packages and/or first boot script". I add some package then click "request build" button. now I have "Unsupported target: lantiq/xrx200". However, before 23.05.4 was released, I compiled 23.05.3 with the same process. Also, no version is even being compiled right now. there is the same error message.

please fix this.

**Comment by aparcar** [comment]
The target was indeed missing, maybe a hiccup on the buildout sorry.
