### ISSUE TITLE
Error when create new custom firmware!

### ISSUE THREAD

**Issue by hainguyen-cmd** [openwrt/firmware-selector-openwrt-org#33]
I have tried to create my custome firmware with some pre-installed packages! However, https://firmware-selector.openwrt.org/ return no action or information after I cliked [REQUEST BUILD]! After trying to know what happening, I have found out that error:
index.js:118 
        
        
       POST https://sysupgrade.openwrt.org/api/v1/build net::ERR_ABORTED 502 (Bad Gateway)

So please solving this! Thanks so much!

**Comment by hainguyen-cmd** [comment]
It's my fault DNS setting! So sorrry about this mistake!

**Comment by hainguyen-cmd** [comment]
Actually, it is not faulty of network! Maybe https://sysupgrade.openwrt.org has problem!

**Comment by tskarthikkumar** [comment]
+1 

I'm also having the same issue when trying to request build. nothing happens after request build button is clicked.

**Comment by greem** [comment]
@aparcar firmware selector / ASU server/s are down - maybe not down, but not working.

**Comment by navigos** [comment]
Yes. Same here. And it's been like this for some time now.

**Comment by lindevel** [comment]
```
$ curl -D - https://sysupgrade.openwrt.org/
HTTP/2 500 
access-control-allow-credentials: true
access-control-allow-headers: *
access-control-allow-methods: POST, GET, OPTIONS
access-control-allow-origin: *
access-control-expose-headers: Authorization
alt-svc: h3=":443"; ma=2592000
content-type: text/plain; charset=utf-8
date: Sat, 07 Sep 2024 06:23:16 GMT
server: Caddy
server: uvicorn
vary: Origin
content-length: 21

Internal Server Error
```

**Comment by mwarning** [comment]
Yeah, no idea why the backend is down. But this concerns the backend (ASU: https://github.com/openwrt/asu) and not the frontend, the OpenWrt Firmware Selector.

As such I will close this issue. Please report on the ASU project page or in the OpenWrt forum. Thank you for your concerns.
