### ISSUE TITLE
Customize in https://firmware-selector.openwrt.org/ fail please fix.

### ISSUE THREAD

**Issue by lessload** [openwrt/firmware-selector-openwrt-org#35]
Customize in https://firmware-selector.openwrt.org/ fail please fix.

**Comment by anoop464** [comment]
page breaks on selecting "REQUEST BUILD" button

**Comment by DisastrousFate** [comment]
I am also having this issue. Upon pressing "Request Build", no links are generated and json console generates error code: 
![image](https://github.com/user-attachments/assets/6fd53144-0a54-4f44-b52a-334121ef3b7f)

**Comment by mwarning** [comment]
This is the wrong project. The problem is with the backend: https://github.com/openwrt/asu

**Comment by anoop464** [comment]
https://github.com/openwrt/asu/issues/961
