### ISSUE TITLE
Device packages not being parsed into package list

### ISSUE THREAD

**Issue by dannil** [openwrt/firmware-selector-openwrt-org#42]
It seems that device packages aren't being parsed into the package list, they're present tho in the response which is returned from profiles.json; note the missing device packages for R7800 in the package list on the left.

![Screenshot_22](https://github.com/user-attachments/assets/279139e9-3d01-4a67-9fa2-768ed83e33cb)

This is a big issue as it affects every single device using device packages and could in worst case lead to a soft-brick.

**Comment by mwarning** [comment]
hm, good point. @aparcar this looks like to huge bug.

**Comment by mwarning** [comment]
Will probably be fixed here: https://github.com/openwrt/firmware-selector-openwrt-org/pull/43

**Comment by mwarning** [comment]
Fixed.
