### ISSUE TITLE
how to set the root partition size

### ISSUE THREAD

**Issue by maimaiya** [openwrt/firmware-selector-openwrt-org#50]
Thank you for your contribution.Currently, I am still self-deploying and temporarily using someone else's server. I want to deploy it myself and first need to understand how to set the root partition size.

**Comment by mwarning** [comment]
Hi @maimaiya, afaik, this is not possible using the firmware selector / ASU. I also do not know how to do it.

**Comment by aparcar** [comment]
Actually it's possible, it just not exposed in the firmware wizard
http://sysupgrade.openwrt.org/docs#/default/api_v1_build_post_api_v1_build_post
