### ISSUE TITLE
Feature Request: allow save current configuration (backup) in a new firmware

### ISSUE THREAD

**Issue by pedro-nonfree** [openwrt/firmware-selector-openwrt-org#59]
So firmware selector right now already have a way to customize packages, and to add small changes through uci-defaults and that is very very useful.

What I am missing is the ability to load a backup inside a new firmware [1], I think firmware selector web form could allow attaching a backup file, and then, allowing the `make FILES=/path/to/uncompressed-backup.tar.gz-dir/` [2] so the firmware contains a firmware that resist the reset configuration.

That is specially useful when we serve openwrt routers to people that, when panic, perform reset button. I already did that, and works very nice, but for me (and maybe for other people) is hard work to follow, involves doing kind of "firmware selector" script [3], adapted to your needs, yes, but hard to maintain when you do this stuff 1-3 times per year that you maintain yourself.

I also see that, this way, we are democratizing and facilitating a feature so people can just do that on their own without a technician in the middle.

[1] https://forum.archive.openwrt.org/viewtopic.php?id=63678
[2] that way, you can of course override any file of the rootfs; add an script, etc. so, very powerful
[3]
  - https://github.com/yanosz/mesh_testbed_generator/ 
  - https://farga.exo.cat/exo/temba

**Comment by mwarning** [comment]
Hi @pedro-nonfree , sysupgrades image are meant to keep the configuration on update. That means that such a feature is out of scope of the firmware selector..
