### ISSUE TITLE
Checksums for OpenWRT 23.05.2 for Espressobin v7 sdcards seem to be incorrect

### ISSUE THREAD

**Issue by paulmsander** [openwrt/firmware-selector-openwrt-org#6]
I downloaded these images using Safari on a Mac, and the SHA-256 checksums of the downloaded files don't match those shown on the download page on the downloads.openwrt.org site.

I also downloaded the factory image for the TP-Link Archer C7, and its checksum matched.

I'm using "shasum -a 256 -b" on the Mac to compute the checksums, and I'm comparing them visually.

The downloaded images are:
4bb1eb338e4c0ea10c18a1277802740f59b1b9d7cf8c875ca4a49b003f4f149e *openwrt-23.05.2-ath79-generic-tplink_archer-c7-v5-squashfs-factory.bin
f6b8a7b5e6c0abfbf2620bce4e7bf4511cc7c17fd6a59350c6f61d0e5f704dc1 *openwrt-23.05.2-mvebu-cortexa53-globalscale_espressobin-v7-emmc-ext4-sdcard.img
cd191b250adbe5be1f13b9eebcb027c1496316e85d1f936b10a9db7798a7c4bc *openwrt-23.05.2-mvebu-cortexa53-globalscale_espressobin-v7-emmc-squashfs-sdcard.img

Again, the checksum for the first image in this list matched the one on the download page, but the first two did not.

**Comment by paulmsander** [comment]
It was not obvious that the download image is in gzip format, and it turns out that Safari decompresses downloaded files automatically by default.  The uncompressed files had different checksums, and gzipping them again also produced different checksums.  But downloading the files using a different browser (Firefox) downloaded the .gz files without further processing, and the checksums matched.

**Comment by mwarning** [comment]
@paulmsander glad you figured out the issue :-)
